sudo: required

language: c

services:
    - docker

before_install:
    - ls
    - docker pull kaixhin/cuda
    - docker run -v=/:/cuda_dsmc -t -i kaixhin/cuda /bin/sh -c "sudo apt-get update; sudo apt-get install -y cmake; nvcc --version; ls cuda_dsmc"

script:
    - ls
    - nvcc --version
#     - cmake .
#     - make
#     - make test
