sudo: required

language: c

services:
    - docker

env:
    - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=QxNPa0jIeV5a2Tjy6QsB2KJ66GR5vICXE

before_install:
    - docker pull injeans/cuda_dsmc:latest

script:
    - docker run -v=/home/travis/build/inJeans/cuda_dsmc:/cuda_dsmc --name="cuda_7.5" injeans/cuda_dsmc /bin/sh -c "cd /cuda_dsmc; mkdir build"
    - docker commit cuda_7.5 injeans/cuda_dsmc:latest
    - docker rm cuda_7.5
    - docker run -v=/home/travis/build/inJeans/cuda_dsmc:/cuda_dsmc --name="cuda_7.5" injeans/cuda_dsmc /bin/sh -c "cd /cuda_dsmc/build; cmake -DSPIN=ON -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .."
    - docker commit cuda_7.5 injeans/cuda_dsmc:latest
    - docker rm cuda_7.5
    - docker run -v=/home/travis/build/inJeans/cuda_dsmc:/cuda_dsmc --name="cuda_7.5" injeans/cuda_dsmc /bin/sh -c "cd /cuda_dsmc/build; make;" 
    - docker commit cuda_7.5 injeans/cuda_dsmc:latest
    - docker rm cuda_7.5
    - docker run -v=/home/travis/build/inJeans/cuda_dsmc:/cuda_dsmc --name="cuda_7.5" injeans/cuda_dsmc /bin/sh -c "cd /cuda_dsmc/build; make coveralls;" 
    - docker commit cuda_7.5 injeans/cuda_dsmc:latest
    - docker rm cuda_7.5
#    - docker run -v=/home/travis/build/inJeans/cuda_dsmc:/cuda_dsmc --name="cuda_7.5" injeans/cuda_dsmc /bin/sh -c "cd /cuda_dsmc; ctest -V" 
#    - docker commit cuda_7.5 injeans/cuda_dsmc:latest
#    - docker rm cuda_7.5
