sudo: required

language: c

services:
    - docker

before_install:
    - docker pull kaixhin/cuda
    - docker run -t -i kaixhin/cuda /bin/sh -c "sudo apt-get update; sudo apt-get install -y cmake; nvcc --version;"

script:
    - ls
    - nvcc --version
#     - cmake .
#     - make
#     - make test
