sudo: required

language: c

services:
    - docker

before_install:
    - docker pull kaixhin/cuda
    - docker run -t -i kaixhin/cuda /bin/sh -c "sudo apt-get update; sudo apt-get install -y cmake; ls /root;"

# script:
#     - ls
#     - cmake .
#     - make
#     - make test
