sudo: required

language: c

services:
    - docker

before_install:
    - docker pull kaixhin/cuda
    - docker run -v=/:/cuda_dsmc -d --name="cuda_7.5" kaixhin/cuda /bin/sh -c "sudo apt-get update;"
    - docker exec -d cuda_7.5 /bin/sh -c "sudo apt-get install -y cmake;"

script:
    - docker exec -it cuda_7.5 /bin/sh -c "nvcc --version;"
    - docker exec -it cuda_7.5 /bin/sh -c "cd /cuda_dsmc; cmake .;"
    - docker exec -it cuda_7.5 /bin/sh -c "cd /cuda_dsmc; make;" 
    - ls
    - docker exec -it cuda_7.5 /bin/sh -c "cd /cuda_dsmc; make test;" 
