sudo: false

language: c

services:
    - docker

before_install:
    - docker pull kaixhin/cuda
    - docker run -t -i kaixhin/cuda /bin/sh -c "apt-get install -y cmake; ls;"

script:
    - ls
    - cmake .
    - make
    - make test
