sudo: required

language: c

services:
    - docker

env:
    - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=DyDqgIext3FRE6wXaymSOndUnxxNqXExA

before_install:
    - docker pull injeans/cuda_dsmc:dev

script:
    # - docker build --file Dockerfile-nix -t cuda_dsmc .
    - docker run injeans/cuda_dsmc:dev
